import Head from 'next/head'
import { useEffect, useState } from 'react'
import Desk from '../components/svg/Desk'

export default function Home() {
    function useWindowSize() {
        const [windowSize, setWindowSize] = useState({
            width: 0,
            height: 0,
        })

        useEffect(() => {
            function handleResize() {
                setWindowSize({
                    width: window.innerWidth,
                    height: window.innerHeight,
                })
            }

            window.addEventListener('resize', handleResize)
            handleResize()

            return () => window.removeEventListener('resize', handleResize)
        }, [])
        return windowSize
    }

    const size = useWindowSize()

    return (
        <div className="bg-tropical min-h-screen">
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="flex flex-col space-y-10 mx-auto max-w-lg p-4 md:p-10">
                {/* <div className="flex items-center justify-between p-6 pb-10 font-bold text-lg tracking-wide">
                    <a className="nav-link underline underline-offset-4 decoration-4 decoration-ebony">
                        who
                    </a>
                    <a className="nav-link underline underline-offset-4 decoration-4 decoration-ebony">
                        what
                    </a>
                    <a className="nav-link underline underline-offset-4 decoration-4 decoration-ebony">
                        work
                    </a>
                </div> */}

                <div className="pt-12 font-bold text-center space-y-1 text-ebony">
                    <h1 className="text-5xl">Hey There,</h1>
                    <h3 className="text-3xl">I&apos;m Joe 👋</h3>
                </div>

                <div className="space-y-8">
                    <Desk size={size.width < 768 ? 'small' : 'large'} />

                    <div className="test p-8 pt-4 pr-4">
                        I&apos;m a full stack software developer from the UK.
                        Let&apos;s make something, anything.
                    </div>
                </div>
            </main>
        </div>
    )
}
